// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Akka")]
[assembly: AssemblyCopyrightAttribute("Copyright © Aaron Stannard 2013-2014")]
[assembly: AssemblyVersionAttribute("1.1.3.0")]
[assembly: AssemblyFileVersionAttribute("1.1.3.0")]
